services:
  api-threshold-low:
    container_name: api-threshold-low
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: rinha
      SCREENING_BUFFER: 20
      SCREENING_WORKERS: 4
      HIGH_PRIORITY_BUFFER: 10
      HIGH_PRIORITY_WORKERS: 5
      LOW_PRIORITY_BUFFER: 20
      LOW_PRIORITY_WORKERS: 10
      LOW_WAITING_BUFFER: 30
      LOW_WAITING_WORKERS: 20
      HIGH_WAITING_BUFFER: 20
      HIGH_WAITING_WORKERS: 10
      K_FACTOR: 0.8
    networks:
      - rinha-back
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 105M
          cpus: "0.5"

  api-threshold-high:
    container_name: api-threshold-high
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: rinha
      SCREENING_BUFFER: 9
      SCREENING_WORKERS: 3
      HIGH_PRIORITY_BUFFER: 6
      HIGH_PRIORITY_WORKERS: 4
      LOW_PRIORITY_BUFFER: 8
      LOW_PRIORITY_WORKERS: 3
      LOW_WAITING_BUFFER: 10
      LOW_WAITING_WORKERS: 9
      HIGH_WAITING_BUFFER: 12
      HIGH_WAITING_WORKERS: 5
      K_FACTOR: 1.4
    networks:
      - rinha-back
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 45M
          cpus: "0.2"     
               
  db:
    container_name: storage
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./payment.sql:/docker-entrypoint-initdb.d/payment.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - rinha-back
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c shared_buffers=32MB
      -c work_mem=3MB
      -c max_connections=30
      -c log_min_duration_statement=-1
      -c logging_collector=off
      -c effective_cache_size=96MB
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "0.5"

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api-threshold-low
      - api-threshold-high
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "30MB"
    networks:
      - rinha-back

volumes:
  pgdata:

networks:
  rinha-back:
    driver: bridge
  payment-processor:
    external: true
